# Generated by Django 4.1.7 on 2023-03-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=500)),
                ('product_sdesc', models.CharField(max_length=1500)),
                ('product_ldesc', models.CharField(max_length=5000)),
                ('product_pub_date', models.DateField()),
                ('product_price', models.IntegerField()),
            ],
        ),
    ]
