# Generated by Django 4.1.7 on 2023-03-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='products',
            name='product_img',
            field=models.ImageField(default='', upload_to='media/MyShop/images'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_subcategory',
            field=models.CharField(default='', max_length=50),
        ),
    ]
