# Generated by Django 4.1.7 on 2023-03-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0002_products_product_category_products_product_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_img',
            field=models.ImageField(default='', upload_to='MyShop/images'),
        ),
    ]
