# Generated by Django 4.1.7 on 2023-03-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0003_alter_products_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(default='', max_length=50)),
                ('issue', models.CharField(default='', max_length=50)),
                ('issue_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
